- name: Deploy GitLab and PostgreSQL
  hosts: all
  become: yes

  roles: 
    - common

- name: Configure PostgreSQL
  hosts: postgres
  become: yes

  roles:
    - bdd

- name: Configure GitLab
  hosts: gitlab
  become: yes

  roles:
    - gitlab